FROM ubuntu

MAINTAINER kevinstone@berkeley.edu

ENV ARCH=aarch64

WORKDIR /

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get update && apt-get install -y \
    curl \
    git \
    python3.6 \
    python3-pip \
    libsm6 \
    libxext6 \
    libxrender-dev \
    mosquitto \
    mosquitto-clients

RUN pip3 install paho-mqtt
RUN pip3 install opencv-python
