# Container for the Jetson TX2 to connect to Mosquitto
# Information from https://github.com/eclipse/mosquitto/blob/master/docker/1.6/Dockerfile

FROM alpine
MAINTAINER penpen1986@berkeley.edu

# Run the server inside apk 

WORKDIR /

RUN echo -e "http://nl.alpinelinux.org/alpine/v3.9/main/" > /etc/apk/repositories

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf && apk update && apk add \
    mosquitto \
    mosquitto-clients
